title: "Ribocentre"
email: "rnapuzzles@gzlab.ac.cn"
description: >
  Ribocentre: a database of ribozymes
baseurl: ""
url: "https://ribocentre.gznl.org"
paper_title: "Ribocentre: a database of ribozymes"
paper_url: "https://doi.org/10.1093/nar/gkac840"
theme_key: "ribocentre"
site_domain: "ribocentre.gznl.org"
legacy_site_domains:
  - "ribocentre.gznl.org"
  - "www.ribocentre.org"
  - "ribocentre.github.io"
site_family_label: "Ribozyme database"
logo_path: "/images/ribocentre-logo.svg"


include:
  - _pages

sass:
  sass_dir: _sass

plugins:
  - liquid

markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true
